import type { Cotacao } from "@/types";
import { mockPecas } from "./pecas";
import { mockFornecedores } from "./fornecedores";
import { mockUsers } from "./users";

export const mockCotacoes: Cotacao[] = [
  {
    id: "c1",
    codigo: "COT-00001",
    titulo: "Filtros e correia caminhão 01",
    solicitanteId: "u3",
    solicitante: mockUsers[2],
    setor: "Manutenção",
    urgencia: "ALTA",
    dataLimiteResposta: "2025-05-20",
    observacoes: "Manutenção preventiva agendada para 22/05",
    status: "ORCAMENTOS_RECEBIDOS",
    itens: [
      {
        id: "ci1",
        pecaId: "p1",
        peca: mockPecas[0],
        quantidade: 2,
        marcaDesejada: "Tecfil",
        aceitaSimilar: true,
        observacao: "Para caminhão 01",
      },
      {
        id: "ci2",
        pecaId: "p3",
        peca: mockPecas[2],
        quantidade: 1,
        marcaDesejada: "Gates",
        aceitaSimilar: false,
      },
      {
        id: "ci3",
        pecaId: "p4",
        peca: mockPecas[3],
        quantidade: 1,
        aceitaSimilar: true,
      },
    ],
    fornecedores: [
      {
        id: "fc1",
        cotacaoId: "c1",
        fornecedorId: "f1",
        fornecedor: mockFornecedores[0],
        status: "ORCAMENTO_CADASTRADO",
        mensagemEnviadaEm: "2025-05-15T09:00:00Z",
        respostaRecebidaEm: "2025-05-15T14:30:00Z",
      },
      {
        id: "fc2",
        cotacaoId: "c1",
        fornecedorId: "f2",
        fornecedor: mockFornecedores[1],
        status: "ORCAMENTO_CADASTRADO",
        mensagemEnviadaEm: "2025-05-15T09:05:00Z",
        respostaRecebidaEm: "2025-05-16T10:00:00Z",
      },
      {
        id: "fc3",
        cotacaoId: "c1",
        fornecedorId: "f3",
        fornecedor: mockFornecedores[2],
        status: "NAO_RESPONDEU",
        mensagemEnviadaEm: "2025-05-15T09:10:00Z",
      },
    ],
    criadoEm: "2025-05-15T08:00:00Z",
    atualizadoEm: "2025-05-16T10:00:00Z",
  },
  {
    id: "c2",
    codigo: "COT-00002",
    titulo: "Óleo e filtros frota",
    solicitanteId: "u2",
    solicitante: mockUsers[1],
    setor: "Compras",
    urgencia: "NORMAL",
    dataLimiteResposta: "2025-05-25",
    status: "AGUARDANDO_RESPOSTAS",
    itens: [
      {
        id: "ci4",
        pecaId: "p5",
        peca: mockPecas[4],
        quantidade: 40,
        marcaDesejada: "Castrol",
        aceitaSimilar: true,
      },
      {
        id: "ci5",
        pecaId: "p1",
        peca: mockPecas[0],
        quantidade: 10,
        aceitaSimilar: true,
      },
      {
        id: "ci6",
        pecaId: "p2",
        peca: mockPecas[1],
        quantidade: 10,
        aceitaSimilar: true,
      },
    ],
    fornecedores: [
      {
        id: "fc4",
        cotacaoId: "c2",
        fornecedorId: "f1",
        fornecedor: mockFornecedores[0],
        status: "MENSAGEM_ENVIADA",
        mensagemEnviadaEm: "2025-05-17T09:00:00Z",
      },
      {
        id: "fc5",
        cotacaoId: "c2",
        fornecedorId: "f3",
        fornecedor: mockFornecedores[2],
        status: "AGUARDANDO_RESPOSTA",
        mensagemEnviadaEm: "2025-05-17T09:05:00Z",
      },
    ],
    criadoEm: "2025-05-17T08:00:00Z",
    atualizadoEm: "2025-05-17T09:05:00Z",
  },
  {
    id: "c3",
    codigo: "COT-00003",
    titulo: "Kit freios veículo leve",
    solicitanteId: "u3",
    solicitante: mockUsers[2],
    setor: "Manutenção",
    urgencia: "URGENTE",
    status: "REQUISICAO_GERADA",
    itens: [
      {
        id: "ci7",
        pecaId: "p4",
        peca: mockPecas[3],
        quantidade: 2,
        aceitaSimilar: false,
        observacao: "Marca original somente",
      },
      {
        id: "ci8",
        pecaId: "p10",
        peca: mockPecas[9],
        quantidade: 2,
        aceitaSimilar: true,
      },
    ],
    fornecedores: [
      {
        id: "fc6",
        cotacaoId: "c3",
        fornecedorId: "f1",
        fornecedor: mockFornecedores[0],
        status: "ORCAMENTO_CADASTRADO",
        mensagemEnviadaEm: "2025-05-10T09:00:00Z",
        respostaRecebidaEm: "2025-05-10T14:00:00Z",
      },
      {
        id: "fc7",
        cotacaoId: "c3",
        fornecedorId: "f2",
        fornecedor: mockFornecedores[1],
        status: "ORCAMENTO_CADASTRADO",
        mensagemEnviadaEm: "2025-05-10T09:00:00Z",
        respostaRecebidaEm: "2025-05-11T09:00:00Z",
      },
    ],
    criadoEm: "2025-05-10T08:00:00Z",
    atualizadoEm: "2025-05-12T08:00:00Z",
  },
  {
    id: "c4",
    codigo: "COT-00004",
    titulo: "Velas e sensor temperatura frota",
    solicitanteId: "u3",
    solicitante: mockUsers[2],
    setor: "Manutenção",
    urgencia: "BAIXA",
    dataLimiteResposta: "2025-05-30",
    status: "RASCUNHO",
    itens: [
      {
        id: "ci9",
        pecaId: "p7",
        peca: mockPecas[6],
        quantidade: 16,
        marcaDesejada: "NGK",
        aceitaSimilar: false,
      },
      {
        id: "ci10",
        pecaId: "p9",
        peca: mockPecas[8],
        quantidade: 4,
        aceitaSimilar: true,
      },
    ],
    fornecedores: [],
    criadoEm: "2025-05-17T10:00:00Z",
    atualizadoEm: "2025-05-17T10:00:00Z",
  },
];