import type { Orcamento } from "@/types";
import { mockPecas } from "./pecas";
import { mockFornecedores } from "./fornecedores";

export const mockOrcamentos: Orcamento[] = [
  {
    id: "o1",
    cotacaoId: "c1",
    fornecedorId: "f1",
    fornecedor: mockFornecedores[0],
    dataOrcamento: "2025-05-15",
    validadePropostaDias: 5,
    prazoEntrega: "Hoje",
    valorFrete: 0,
    formaPagamento: "Pix",
    observacoes: "Entrega imediata",
    status: "CONFERIDO",
    itens: [
      {
        id: "oi1",
        cotacaoItemId: "ci1",
        peca: mockPecas[0],
        marcaCotada: "Wega",
        quantidade: 2,
        valorUnitario: 45.0,
        valorTotal: 90.0,
        disponivel: true,
      },
      {
        id: "oi2",
        cotacaoItemId: "ci2",
        peca: mockPecas[2],
        marcaCotada: "Gates",
        quantidade: 1,
        valorUnitario: 150.0,
        valorTotal: 150.0,
        disponivel: true,
      },
      {
        id: "oi3",
        cotacaoItemId: "ci3",
        peca: mockPecas[3],
        marcaCotada: "Fras-le",
        quantidade: 1,
        valorUnitario: 210.0,
        valorTotal: 210.0,
        disponivel: true,
      },
    ],
    anexos: [
      {
        id: "an1",
        nome: "orcamento_central.pdf",
        tipo: "ORCAMENTO_PDF",
        tamanho: 102400,
        url: "/mock/orcamento_central.pdf",
        enviadoPorId: "u2",
        enviadoEm: "2025-05-15T14:30:00Z",
      },
    ],
    criadoEm: "2025-05-15T14:30:00Z",
  },
  {
    id: "o2",
    cotacaoId: "c1",
    fornecedorId: "f2",
    fornecedor: mockFornecedores[1],
    dataOrcamento: "2025-05-16",
    validadePropostaDias: 3,
    prazoEntrega: "2 dias úteis",
    valorFrete: 20.0,
    formaPagamento: "Boleto",
    status: "CONFERIDO",
    itens: [
      {
        id: "oi4",
        cotacaoItemId: "ci1",
        peca: mockPecas[0],
        marcaCotada: "Tecfil",
        quantidade: 2,
        valorUnitario: 42.0,
        valorTotal: 84.0,
        disponivel: true,
        observacao: "Marca original conforme solicitado",
      },
      {
        id: "oi5",
        cotacaoItemId: "ci2",
        peca: mockPecas[2],
        marcaCotada: "Contitech",
        quantidade: 1,
        valorUnitario: 140.0,
        valorTotal: 140.0,
        disponivel: true,
        observacao: "Similar aprovado pela fabricante",
      },
      {
        id: "oi6",
        cotacaoItemId: "ci3",
        peca: mockPecas[3],
        marcaCotada: "Cofap",
        quantidade: 1,
        valorUnitario: 185.0,
        valorTotal: 185.0,
        disponivel: false,
        observacao: "Disponível em 3 dias",
      },
    ],
    anexos: [],
    criadoEm: "2025-05-16T10:00:00Z",
  },
  {
    id: "o3",
    cotacaoId: "c3",
    fornecedorId: "f1",
    fornecedor: mockFornecedores[0],
    dataOrcamento: "2025-05-10",
    validadePropostaDias: 5,
    prazoEntrega: "Hoje",
    valorFrete: 0,
    formaPagamento: "Pix",
    status: "SELECIONADO",
    itens: [
      {
        id: "oi7",
        cotacaoItemId: "ci7",
        peca: mockPecas[3],
        marcaCotada: "Fras-le",
        quantidade: 2,
        valorUnitario: 195.0,
        valorTotal: 390.0,
        disponivel: true,
      },
      {
        id: "oi8",
        cotacaoItemId: "ci8",
        peca: mockPecas[9],
        marcaCotada: "Bosch",
        quantidade: 2,
        valorUnitario: 28.0,
        valorTotal: 56.0,
        disponivel: true,
      },
    ],
    anexos: [],
    criadoEm: "2025-05-10T14:00:00Z",
  },
  {
    id: "o4",
    cotacaoId: "c3",
    fornecedorId: "f2",
    fornecedor: mockFornecedores[1],
    dataOrcamento: "2025-05-11",
    validadePropostaDias: 3,
    prazoEntrega: "2 dias úteis",
    valorFrete: 15.0,
    formaPagamento: "Pix ou Boleto",
    status: "RECUSADO",
    itens: [
      {
        id: "oi9",
        cotacaoItemId: "ci7",
        peca: mockPecas[3],
        marcaCotada: "Fras-le",
        quantidade: 2,
        valorUnitario: 180.0,
        valorTotal: 360.0,
        disponivel: true,
      },
      {
        id: "oi10",
        cotacaoItemId: "ci8",
        peca: mockPecas[9],
        marcaCotada: "TRW",
        quantidade: 2,
        valorUnitario: 30.0,
        valorTotal: 60.0,
        disponivel: true,
      },
    ],
    anexos: [],
    criadoEm: "2025-05-11T09:00:00Z",
  },
];