import type { Peca } from "@/types";

export const mockPecas: Peca[] = [
  {
    id: "p1",
    nome: "Filtro de óleo",
    codigoInterno: "FO-001",
    codigoOriginal: "8-94150811-0",
    categoria: "Filtros",
    marcaPreferencial: "Tecfil",
    aplicacao: "Motor diesel e gasolina",
    unidade: "UNIDADE",
    status: "ATIVA",
    estoqueMinimo: 5,
    criadoEm: "2024-01-01T08:00:00Z",
  },
  {
    id: "p2",
    nome: "Filtro de ar",
    codigoInterno: "FA-001",
    categoria: "Filtros",
    marcaPreferencial: "Tecfil",
    unidade: "UNIDADE",
    status: "ATIVA",
    estoqueMinimo: 3,
    criadoEm: "2024-01-01T08:00:00Z",
  },
  {
    id: "p3",
    nome: "Correia dentada",
    codigoInterno: "CD-001",
    codigoOriginal: "5574XS",
    categoria: "Correias",
    marcaPreferencial: "Gates",
    aplicacao: "Motor 1.0 / 1.4 / 1.6",
    unidade: "UNIDADE",
    status: "ATIVA",
    estoqueMinimo: 2,
    criadoEm: "2024-01-01T08:00:00Z",
  },
  {
    id: "p4",
    nome: "Pastilha de freio dianteira",
    codigoInterno: "PF-001",
    categoria: "Freios",
    marcaPreferencial: "Fras-le",
    unidade: "JOGO",
    status: "ATIVA",
    estoqueMinimo: 2,
    criadoEm: "2024-01-01T08:00:00Z",
  },
  {
    id: "p5",
    nome: "Óleo lubrificante 15W40",
    codigoInterno: "OL-001",
    categoria: "Óleos",
    marcaPreferencial: "Castrol",
    aplicacao: "Motor diesel",
    unidade: "LITRO",
    status: "ATIVA",
    estoqueMinimo: 20,
    criadoEm: "2024-01-01T08:00:00Z",
  },
  {
    id: "p6",
    nome: "Rolamento de roda",
    codigoInterno: "RR-001",
    categoria: "Rolamentos",
    unidade: "UNIDADE",
    status: "ATIVA",
    estoqueMinimo: 4,
    criadoEm: "2024-01-05T08:00:00Z",
  },
  {
    id: "p7",
    nome: "Vela de ignição",
    codigoInterno: "VI-001",
    categoria: "Elétrico",
    marcaPreferencial: "NGK",
    unidade: "UNIDADE",
    status: "ATIVA",
    estoqueMinimo: 4,
    criadoEm: "2024-01-05T08:00:00Z",
  },
  {
    id: "p8",
    nome: "Correia do alternador",
    codigoInterno: "CA-001",
    categoria: "Correias",
    marcaPreferencial: "Gates",
    unidade: "UNIDADE",
    status: "ATIVA",
    criadoEm: "2024-01-10T08:00:00Z",
  },
  {
    id: "p9",
    nome: "Sensor de temperatura",
    codigoInterno: "ST-001",
    categoria: "Sensores",
    unidade: "UNIDADE",
    status: "ATIVA",
    criadoEm: "2024-02-01T08:00:00Z",
  },
  {
    id: "p10",
    nome: "Fluido de freio DOT4",
    codigoInterno: "FF-001",
    categoria: "Fluidos",
    unidade: "LITRO",
    status: "ATIVA",
    estoqueMinimo: 5,
    criadoEm: "2024-02-01T08:00:00Z",
  },
];