import type { Requisicao, RequisicaoItem } from "@/types";
import { mockPecas } from "./pecas";
import { mockFornecedores } from "./fornecedores";
import { mockUsers } from "./users";
import { mockCotacoes } from "./cotacoes";

export const mockRequisicoes: Requisicao[] = [
  {
    id: "r1",
    numero: "REQ-00001",
    cotacaoId: "c3",
    cotacao: mockCotacoes[2],
    solicitanteId: "u3",
    solicitante: mockUsers[2],
    setor: "Manutenção",
    urgencia: "URGENTE",
    status: "AGUARDANDO_APROVACAO",
    valorTotal: 446.0,
    justificativa:
      "Freios comprometidos no veículo leve 03. Risco de segurança. Escolhido Auto Peças Central por entrega imediata e sem frete.",
    itens: [
      {
        id: "ri1",
        pecaId: "p4",
        peca: mockPecas[3],
        fornecedorId: "f1",
        fornecedor: mockFornecedores[0],
        orcamentoItemId: "oi7",
        marca: "Fras-le",
        quantidade: 2,
        valorUnitario: 195.0,
        valorTotal: 390.0,
        justificativa: "Entrega imediata, sem frete",
        statusEntrega: "AGUARDANDO_COMPRA",
        quantidadeRecebida: 0,
      },
      {
        id: "ri2",
        pecaId: "p10",
        peca: mockPecas[9],
        fornecedorId: "f1",
        fornecedor: mockFornecedores[0],
        orcamentoItemId: "oi8",
        marca: "Bosch",
        quantidade: 2,
        valorUnitario: 28.0,
        valorTotal: 56.0,
        justificativa: "Mesmo fornecedor para reduzir frete",
        statusEntrega: "AGUARDANDO_COMPRA",
        quantidadeRecebida: 0,
      },
    ],
    anexos: [],
    historico: [
      {
        id: "h1",
        data: "2025-05-12T08:00:00Z",
        acao: "Requisição criada",
        usuarioId: "u3",
        usuario: mockUsers[2],
        statusAnterior: undefined,
        statusNovo: "RASCUNHO",
      },
      {
        id: "h2",
        data: "2025-05-12T08:30:00Z",
        acao: "Enviada para aprovação",
        usuarioId: "u3",
        usuario: mockUsers[2],
        statusAnterior: "RASCUNHO",
        statusNovo: "AGUARDANDO_APROVACAO",
      },
    ],
    criadoEm: "2025-05-12T08:00:00Z",
    atualizadoEm: "2025-05-12T08:30:00Z",
  },
  {
    id: "r2",
    numero: "REQ-00002",
    cotacaoId: "c1",
    cotacao: mockCotacoes[0],
    solicitanteId: "u3",
    solicitante: mockUsers[2],
    setor: "Manutenção",
    urgencia: "ALTA",
    status: "PEDIDO_FECHADO",
    valorTotal: 450.0,
    justificativa:
      "Manutenção preventiva do caminhão 01. Auto Peças Central escolhida por entrega imediata e sem frete.",
    itens: [
      {
        id: "ri3",
        pecaId: "p1",
        peca: mockPecas[0],
        fornecedorId: "f1",
        fornecedor: mockFornecedores[0],
        orcamentoItemId: "oi1",
        marca: "Wega",
        quantidade: 2,
        valorUnitario: 45.0,
        valorTotal: 90.0,
        statusEntrega: "AGUARDANDO_ENTREGA",
        quantidadeRecebida: 0,
        previsaoEntrega: "2025-05-18",
      },
      {
        id: "ri4",
        pecaId: "p3",
        peca: mockPecas[2],
        fornecedorId: "f1",
        fornecedor: mockFornecedores[0],
        orcamentoItemId: "oi2",
        marca: "Gates",
        quantidade: 1,
        valorUnitario: 150.0,
        valorTotal: 150.0,
        statusEntrega: "AGUARDANDO_ENTREGA",
        quantidadeRecebida: 0,
        previsaoEntrega: "2025-05-18",
      },
      {
        id: "ri5",
        pecaId: "p4",
        peca: mockPecas[3],
        fornecedorId: "f1",
        fornecedor: mockFornecedores[0],
        orcamentoItemId: "oi3",
        marca: "Fras-le",
        quantidade: 1,
        valorUnitario: 210.0,
        valorTotal: 210.0,
        statusEntrega: "AGUARDANDO_ENTREGA",
        quantidadeRecebida: 0,
        previsaoEntrega: "2025-05-18",
      },
    ],
    anexos: [],
    aprovadorId: "u4",
    aprovador: mockUsers[3],
    dataAprovacao: "2025-05-16T10:00:00Z",
    comentarioAprovador: "Aprovado. Urgência justificada.",
    dataFechamentoPedido: "2025-05-16T11:00:00Z",
    previsaoEntregaGeral: "2025-05-18",
    formaPagamento: "Pix",
    historico: [
      {
        id: "h3",
        data: "2025-05-15T16:00:00Z",
        acao: "Requisição criada",
        usuarioId: "u2",
        usuario: mockUsers[1],
        statusNovo: "RASCUNHO",
      },
      {
        id: "h4",
        data: "2025-05-15T16:30:00Z",
        acao: "Enviada para aprovação",
        usuarioId: "u2",
        usuario: mockUsers[1],
        statusAnterior: "RASCUNHO",
        statusNovo: "AGUARDANDO_APROVACAO",
      },
      {
        id: "h5",
        data: "2025-05-16T10:00:00Z",
        acao: "Aprovada",
        usuarioId: "u4",
        usuario: mockUsers[3],
        comentario: "Aprovado. Urgência justificada.",
        statusAnterior: "AGUARDANDO_APROVACAO",
        statusNovo: "APROVADA",
      },
      {
        id: "h6",
        data: "2025-05-16T11:00:00Z",
        acao: "Pedido fechado",
        usuarioId: "u2",
        usuario: mockUsers[1],
        statusAnterior: "APROVADA",
        statusNovo: "PEDIDO_FECHADO",
      },
    ],
    criadoEm: "2025-05-15T16:00:00Z",
    atualizadoEm: "2025-05-16T11:00:00Z",
  },
  {
    id: "r3",
    numero: "REQ-00003",
    cotacaoId: "c3",
    cotacao: mockCotacoes[2],
    solicitanteId: "u3",
    solicitante: mockUsers[2],
    setor: "Manutenção",
    urgencia: "NORMAL",
    status: "PARCIALMENTE_RECEBIDA",
    valorTotal: 950.0,
    justificativa: "Reposição de estoque de filtros e óleos.",
    itens: [
      {
        id: "ri6",
        pecaId: "p5",
        peca: mockPecas[4],
        fornecedorId: "f3",
        fornecedor: mockFornecedores[2],
        orcamentoItemId: "oi1",
        marca: "Castrol",
        quantidade: 20,
        valorUnitario: 35.0,
        valorTotal: 700.0,
        statusEntrega: "RECEBIDA",
        quantidadeRecebida: 20,
        dataRecebimento: "2025-05-14T10:00:00Z",
        quemRecebeu: "Paulo Almoxarife",
        condicaoPeca: "OK",
      },
      {
        id: "ri7",
        pecaId: "p1",
        peca: mockPecas[0],
        fornecedorId: "f3",
        fornecedor: mockFornecedores[2],
        orcamentoItemId: "oi2",
        marca: "Tecfil",
        quantidade: 5,
        valorUnitario: 50.0,
        valorTotal: 250.0,
        statusEntrega: "RECEBIDA_PARCIALMENTE",
        quantidadeRecebida: 3,
        observacaoRecebimento: "2 unidades em falta, fornecedor confirmou envio para amanhã",
      },
    ],
    anexos: [
      {
        id: "an2",
        nome: "nota_fiscal_003.pdf",
        tipo: "NOTA_FISCAL",
        tamanho: 204800,
        url: "/mock/nf_003.pdf",
        enviadoPorId: "u5",
        enviadoEm: "2025-05-14T10:30:00Z",
      },
    ],
    aprovadorId: "u4",
    aprovador: mockUsers[3],
    dataAprovacao: "2025-05-12T09:00:00Z",
    historico: [],
    criadoEm: "2025-05-11T08:00:00Z",
    atualizadoEm: "2025-05-14T10:30:00Z",
  },
];
export function updateItemEntrega(
  requisicaoId: string,
  itemId: string,
  update: Partial<RequisicaoItem>
): boolean {
  const req = mockRequisicoes.find((r) => r.id === requisicaoId);
  if (!req) return false;
  const item = req.itens.find((i) => i.id === itemId);
  if (!item) return false;
  Object.assign(item, update);
  const all = req.itens.every((i) => i.statusEntrega === "RECEBIDA");
  const any = req.itens.some((i) => ["RECEBIDA", "RECEBIDA_PARCIALMENTE"].includes(i.statusEntrega));
  if (all) req.status = "RECEBIDA";
  else if (any) req.status = "PARCIALMENTE_RECEBIDA";
  req.atualizadoEm = new Date().toISOString();
  return true;
}
